#!/usr/bin/bash

# ALIAS {{{
alias freemem='sudo /sbin/sysctl -w vm.drop_caches=3'
alias enter_matrix='echo -e "\e[32m"; while :; do for i in {1..16}; do r="$(($RANDOM % 2))"; if [[ $(($RANDOM % 5)) == 1 ]]; then if [[ $(($RANDOM % 4)) == 1 ]]; then v+="\e[1m $r   "; else v+="\e[2m $r   "; fi; else v+="     "; fi; done; echo -e "$v"; v=""; done'

# GIT_OR_HUB {{{
if which hub &>/dev/null; then
  alias git=hub
fi
#}}}

# AUTOCOLOR {{{
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ncdu='ncdu --color dark'
alias tree='tree -C'
alias ip='ip -c'
#}}}

# MODIFIED COMMANDS {{{
alias ..='echo "cd .."; cd ..'
alias ....='echo "cd ../.."; cd ../..'
alias ......='echo "cd ../../.."; cd ../../..'
alias hl='rg --passthru'
alias fman='compgen -c | fzf | xargs man'
alias open='xdg-open'
#alias df='df -h'
alias diff='colordiff'              # requires colordiff package
alias du='du -c -h'
alias free='free -m'                # show sizes in MB
#alias grep='grep --color=tty -d skip'
#alias mkdir='mkdir -p -v'
alias more='less'
alias nano='nano -w -_'
#alias ping='ping -c 5'
#alias fastfetch='fastfetch --logo HarDClanZ'
alias c='clear'
alias cl='clear && l'
alias .bashrc="nvim ~/.bashrc"
alias .aliases="nvim ~/.bash_aliases"
#alias vimconf="cd ~/.config/nvim && nvim init.lua"
alias vimconf="nvim ~/.config/nvim/init.lua"
alias dwmconf="nvim ~/.config/dwm/config.def.h"
alias stconf="nvim ~/.config/st/config.h"
#alias bat='batcat'
alias rsync='rsync --progress'
#}}}

# PRIVILEGED ACCESS {{{
#alias sudo='sudo '
alias scat='sudo cat'
alias svim='sudoedit'
alias root='sudo su'
#alias reboot='sudo reboot'
#alias halt='sudo halt'
#alias powertop='sudo powertop'
#}}}

# PACMAN ALIASES {{{
# we're on ARCH
if $_isarch; then
  # we're not root
  if ! $_isroot; then
    alias pacman='sudo pacman'
  fi
  alias pacupg='pacman -Syu'            # Synchronize with repositories and then upgrade packages that are out of date on the local system.
  alias pacupd='pacman -Sy'             # Refresh of all package lists after updating /etc/pacman.d/mirrorlist
  alias pacin='pacman -S'               # Install specific package(s) from the repositories
  alias pacinu='pacman -U'              # Install specific local package(s)
  alias pacre='pacman -R'               # Remove the specified package(s), retaining its configuration(s) and required dependencies
  alias pacun='pacman -Rcsn'            # Remove the specified package(s), its configuration(s) and unneeded dependencies
  alias pacinfo='pacman -Si'            # Display information about a given package in the repositories
  alias pacse='pacman -Ss'              # Search for package(s) in the repositories

  alias pacupa='pacman -Sy && sudo abs' # Update and refresh the local package and ABS databases against repositories
  alias pacind='pacman -S --asdeps'     # Install given package(s) as dependencies of another package
  alias pacclean="pacman -Sc"           # Delete all not currently installed package files
  alias pacmake="makepkg -fcsi"         # Make package from PKGBUILD file in current directory
  alias changemirror='svim /etc/pacman.d/mirrorlist'
  alias update-grub='grub-mkconfig -o /boot/grub/grub.cfg'
fi
#}}}

# MULTIMEDIA {{{
if which get_flash_videos &>/dev/null; then
  alias gfv='get_flash_videos -r 720p --subtitles'
fi
#}}}

# LS {{{
alias ls='ls -hF --color=auto'
alias lr='ls -R'                    # recursive ls
alias lm='la | bat'
alias ll='ls -lA'
alias la='ls -A'
alias l='ls -l'
#}}}

# MISC {{{
alias activate='source .venv/bin/activate' # alias for activating venv
alias venv='python3 -m venv .venv'
alias utime='sudo ntpdate pool.ntp.org'
#alias z='zoxide'
alias python='python3'
alias jp2a='jp2a --color'
alias kvm-unload='lsmod | grep kvm && sudo rmmod kvm_intel && sudo rmmod kvm'
alias jupyter-tunnel='ssh -L 8888:localhost:8888 nicomr@taigete-tunnel'
alias mongosh-docker='mongosh --port 27017'
alias listen='sudo lsof -i -P -n | grep LISTEN'
alias public-ip='curl ifconfig.me && echo'
alias wg-up='sudo wg-quick up wg0'
alias wg-down='sudo wg-quick down wg0'
#}}}

# SERVER {{{
alias underleaf-backup='sudo cp -r /home/nicomr/redis_data/ /home/nicomr/sharelatex_data/ /home/nicomr/mongo_data/ /mnt/disk1/'
alias tunnel='screen -r playit.gg'
alias awake-server='wakeonlan $(cat ~/.serverMAC)'
alias aa2='z aa2 && activate'

alias crafty-backup='sudo cp -r /DATA/AppData/crafty/backups/* /mnt/disk1/crafty/backups'
alias crafty-optimize='sudo cp -r /home/nicomr/crafty/purpur/* .'

alias casaos-update='curl -fsSL https://get.casaos.io/update | sudo bash'
alias casaos-start='sudo systemctl start casaos-app-management.service casaos-local-storage.service casaos-user-service.service casaos-gateway.service casaos-message-bus.service && sudo systemctl start casaos'
alias casaos-stop='sudo systemctl stop casaos-app-management.service casaos-local-storage.service casaos-user-service.service casaos-gateway.service casaos-message-bus.service && sudo systemctl stop casaos'
alias casaos-enable='sudo systemctl enable casaos-app-management.service casaos-local-storage.service casaos-user-service.service casaos-gateway.service casaos-message-bus.service && sudo systemctl enable casaos'
alias casaos-disable='sudo systemctl disable casaos-app-management.service casaos-local-storage.service casaos-user-service.service casaos-gateway.service casaos-message-bus.service && sudo systemctl disable casaos'

#alias mountdisk='sudo mount /dev/sdb /mnt/disk1'
#alias umountdisk='sudo umount /mnt/disk1'
alias mountdir='sudo mount -t nfs4 10.8.0.1:/media/nfs /media/share'
alias umountdir='sudo umount /media/share'
#alias mountdirs='sudo mount -a'
#}}}

# MISSPELLINGS {{{
alias suod='sudo'
alias clera='clear'
alias lcear='clear'
alias tre='tree'
alias exho='echo'
#}}}
#}}}
